/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com). <br><br> <b>SSE NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave similarly to its standard operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) <br><br> <b>WEB SOCKETS NOTE:</b> Some end-points described here will indicate \"(Supports WebSockets)\" to indicate that they can invoked via the Web Sockets protocol. This support is activated by invoking the end-point using the `ws://` protocol in the URL.  Any request query parameters can still be sent on the URL and the request body can be sent as one or more message from the client (as documented).  The end-point response will be sent as one or more response messages as documented (sometimes describing progress as with SSE end-points).  Upon failure responses will follow the same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`)
 *
 * OpenAPI spec version: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes the necessity for this attribute type within the feature type.  Possible values are:   * `REQUIRED` - The attribute for the attribute type must be                  provided whenever the feature is provided (e.g.:                  \"PASSPORT_NUMBER\" is required with the \"PASSPORT\"                  feature).   * `SUFFICIENT` - If no attributes for `REQUIRED` attribute types                    are provided for the feature, then at least one                    marked `SUFFICIENT` must be provided (e.g.:                    \"NAME_FULL\" or \"NAME_ORG\" for the \"NAME\" feature)   * `PREFERRED` - Attributes of `PREFERRED` attribute types are                   optional, but providing them greatly enhances                   accuracy for scoring and matching purposes (e.g.:                   a \"PASSPORT_COUNTRY\" for \"PASSPORT\" feature)   * `OPTIONAL` - Attributes of `OPTIONAL` attribute types are                  optional and do not significantly affect accuracy                  for scoring and matching purposes, but do provide                  additional information (e.g.: \"PASSPORT_ISSUE_DT\"                  for the \"PASSPORT\" feature)
 */
export type SzAttributeNecessity = 'REQUIRED' | 'SUFFICIENT' | 'PREFERRED' | 'OPTIONAL';

export const SzAttributeNecessity = {
    REQUIRED: 'REQUIRED' as SzAttributeNecessity,
    SUFFICIENT: 'SUFFICIENT' as SzAttributeNecessity,
    PREFERRED: 'PREFERRED' as SzAttributeNecessity,
    OPTIONAL: 'OPTIONAL' as SzAttributeNecessity
};