/**
 * Senzing POC REST API
 * This is the Senzing POC REST API.  This API is <b>NOT</b> maintained for backwards compatibility.  This API extends the [Senzing REST API](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/senzing-garage/senzing-rest-api-specification/main/senzing-rest-api.yaml) which is maintained for backwards compatibility.  However, the Senzing POC API is specifically targeted at the Senzing One-Day POC application and no guarantees are made for support.  It can be used as example for creating your own extended API. <br><br> <b>SSE NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave similarly to its standard operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) <br><br> <b>WEB SOCKETS NOTE:</b> Some end-points described here will indicate \"(Supports WebSockets)\" to indicate that they can invoked via the Web Sockets protocol. This support is activated by invoking the end-point using the `ws://` protocol in the URL.  Any request query parameters can still be sent on the URL and the request body can be sent as one or more message from the client (as documented).  The end-point response will be sent as one or more response messages as documented (sometimes describing progress as with SSE end-points).  Upon failure responses will follow the same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`)
 *
 * OpenAPI spec version: 3.5.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes the type of bound for a range. Possible values are:   * `INCLUSIVE_LOWER` - The bound represents an inclusive lower bound whereby                         values satisifying the bound will be greater-than or equal                         to the value associated with the bound.   * `EXCLUSIVE_LOWER` - The bound represents an exclusive lower bound whereby                          values satisfying the bound will be strictly greater-than                          the value associated with the bound.   * `INCLUSIVE_UPPER` - The bound represents an inclusive upper bound whereby                         values satisifying the bound will be less-than or equal                         to the value associated with the bound.   * `EXCLUSIVE_UPPER` - The bound represents an exclusive upper bound whereby                          values satisfying the bound will be strictly less-than                          the value associated with the bound.
 */
export type SzBoundType = 'INCLUSIVE_LOWER' | 'EXCLUSIVE_LOWER' | 'INCLUSIVE_UPPER' | 'EXCLUSIVE_UPPER';

export const SzBoundType = {
    INCLUSIVELOWER: 'INCLUSIVE_LOWER' as SzBoundType,
    EXCLUSIVELOWER: 'EXCLUSIVE_LOWER' as SzBoundType,
    INCLUSIVEUPPER: 'INCLUSIVE_UPPER' as SzBoundType,
    EXCLUSIVEUPPER: 'EXCLUSIVE_UPPER' as SzBoundType
};