/**
 * Senzing POC REST API
 * This is the Senzing POC REST API.  This API is <b>NOT</b> maintained for backwards compatibility.  This API extends the [Senzing REST API](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/senzing-garage/senzing-rest-api-specification/main/senzing-rest-api.yaml) which is maintained for backwards compatibility.  However, the Senzing POC API is specifically targeted at the Senzing One-Day POC application and no guarantees are made for support.  It can be used as example for creating your own extended API. <br><br> <b>SSE NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave similarly to its standard operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) <br><br> <b>WEB SOCKETS NOTE:</b> Some end-points described here will indicate \"(Supports WebSockets)\" to indicate that they can invoked via the Web Sockets protocol. This support is activated by invoking the end-point using the `ws://` protocol in the URL.  Any request query parameters can still be sent on the URL and the request body can be sent as one or more message from the client (as documented).  The end-point response will be sent as one or more response messages as documented (sometimes describing progress as with SSE end-points).  Upon failure responses will follow the same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`)
 *
 * OpenAPI spec version: 3.5.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The method by which feature values should be included for entities returned in the response.  The possible values are:   * `NONE` - Do not include any feature values -- this is the fastest              option from a performance perspective because feature              values do not have to be retrieved.   * `ENTITY_NAME_ONLY` - Same as `NONE` in that no \"features\" are                          returned, but the singular entity name value                          is determined will be determined and returned.   * `REPRESENTATIVE` - Include only a single representative value per                        \"unique\" value of a feature.  If there are                        multiple values that are near duplicates then                        only one value is included and the others are                        suppressed.   * `WITH_DUPLICATES` - ** (default value) ** Group near-duplicate                         feature values and return a representative value                         along with its near duplicate values.   * `ATTRIBUTED` - Same as `WITH_DUPLICATES` but with record-level                    references attributing each feature to the record(s)                    that provided it for the entity along with any                    usage type that might have been associated with the                    feature at the record level.
 */
export type SzFeatureMode = 'NONE' | 'ENTITY_NAME_ONLY' | 'REPRESENTATIVE' | 'WITH_DUPLICATES' | 'ATTRIBUTED';

export const SzFeatureMode = {
    NONE: 'NONE' as SzFeatureMode,
    ENTITYNAMEONLY: 'ENTITY_NAME_ONLY' as SzFeatureMode,
    REPRESENTATIVE: 'REPRESENTATIVE' as SzFeatureMode,
    WITHDUPLICATES: 'WITH_DUPLICATES' as SzFeatureMode,
    ATTRIBUTED: 'ATTRIBUTED' as SzFeatureMode
};