/**
 * Senzing REST API
 * This is the Senzing REST API.  It describes the REST interface to Senzing API functions available via REST.  It leverages the Senzing native API which is documented at [https://docs.senzing.com](https://docs.senzing.com). <br><br> <b>SSE NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave similarly to its standard operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) <br><br> <b>WEB SOCKETS NOTE:</b> Some end-points described here will indicate \"(Supports WebSockets)\" to indicate that they can invoked via the Web Sockets protocol. This support is activated by invoking the end-point using the `ws://` protocol in the URL.  Any request query parameters can still be sent on the URL and the request body can be sent as one or more message from the client (as documented).  The end-point response will be sent as one or more response messages as documented (sometimes describing progress as with SSE end-points).  Upon failure responses will follow the same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`)
 *
 * OpenAPI spec version: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes the various match levels describing how two records resolve against each other.  The possible values are:   * `NO_MATCH` - No match was found between the records.   * `RESOLVED` - The records resolved to the same entity.   * `POSSIBLY_SAME` - The records were not close enough to resolve     but may represent the same entity if more data was provided.   * `POSSIBLY_RELATED` - The records share some attributes that     suggest a relationship.   * `NAME_ONLY` - The records match in name only.   * `DISCLOSED` - An explicit relationship has been disclosed between     the records.
 */
export type SzMatchLevel = 'NO_MATCH' | 'RESOLVED' | 'POSSIBLY_SAME' | 'POSSIBLY_RELATED' | 'NAME_ONLY' | 'DISCLOSED';

export const SzMatchLevel = {
    NOMATCH: 'NO_MATCH' as SzMatchLevel,
    RESOLVED: 'RESOLVED' as SzMatchLevel,
    POSSIBLYSAME: 'POSSIBLY_SAME' as SzMatchLevel,
    POSSIBLYRELATED: 'POSSIBLY_RELATED' as SzMatchLevel,
    NAMEONLY: 'NAME_ONLY' as SzMatchLevel,
    DISCLOSED: 'DISCLOSED' as SzMatchLevel
};