/**
 * Senzing POC REST API
 * This is the Senzing POC REST API.  This API is <b>NOT</b> maintained for backwards compatibility.  This API extends the [Senzing REST API](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/senzing-garage/senzing-rest-api-specification/main/senzing-rest-api.yaml) which is maintained for backwards compatibility.  However, the Senzing POC API is specifically targeted at the Senzing One-Day POC application and no guarantees are made for support.  It can be used as example for creating your own extended API. <br><br> <b>SSE NOTE:</b> Some end-points described here will indicate \"(Supports SSE)\" to indicate that they support \"Server-sent Events\" via the `text/event-stream` media type.  This support is activated by adding the `Accept: text/event-stream` header to a request to override the default `application/json` media type.  Further, the end-point will behave similarly to its standard operation but will produce `progress` events at regular intervals that are equivalent to its `200` response schema. Upon success, the final event will be `completed` with the same response schema as a `200` response.  Upon failure, the final event will be `failed` with same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`) <br><br> <b>WEB SOCKETS NOTE:</b> Some end-points described here will indicate \"(Supports WebSockets)\" to indicate that they can invoked via the Web Sockets protocol. This support is activated by invoking the end-point using the `ws://` protocol in the URL.  Any request query parameters can still be sent on the URL and the request body can be sent as one or more message from the client (as documented).  The end-point response will be sent as one or more response messages as documented (sometimes describing progress as with SSE end-points).  Upon failure responses will follow the same schema as the `4xx` or `5xx` response (typically the `SzErrorResponse`)
 *
 * OpenAPI spec version: 3.5.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes the entity, record and relationship counts for the respective relation type for entities having at least one record from the primary data source to  entities having at least one record from the \"versus\" data source.
 */
export interface SzRelationCounts { 
    /**
     * The optional match key associated with the statistics.  This may be `null` or absent if the statistics are not associated with a match key.
     */
    matchKey?: string;
    /**
     * The optional principle associated with the statistics.  This may be `null` or absent if the statistics are not associated with a principle.
     */
    principle?: string;
    /**
     * The number of entities having at least one record from the primary data source related by a relationship of the respective relationship type to  an entity with at least one record from the \"versus\" data source.
     */
    entityCount?: number;
    /**
     * The number of records from the primary data source in the entities described by the `entityCount`.  NOTE: this is not the total number of records in those entities, but only the count of those records from the primary data source.
     */
    recordCount?: number;
    /**
     * The number of relationships of the respective relationship type between entities having at least one record from the primary data source and entities having at least one record from the \"versus\" data source.
     */
    relationCount?: number;
}