name: CI Angular app through Github Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm ci

      - name: Test
        run: |
          npm test -- --no-watch --watch=false --progress=false --no-progress --browsers=ChromeHeadlessCI
      - name: Build Docs
        run: |
          npm run build:docs
      - name: Build Package
        run: |
          npm run build