name: npm build

on: push

permissions:
  contents: read

jobs:
  npm-build:
    name: CI Angular app through Github Actions
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: use Node.js 18.x
        uses: actions/setup-node@v5
        with:
          node-version: 18.x

      - name: setup
        run: npm ci

      - name: run static tests
        run: |
          npm test -- --no-watch --watch=false --progress=false --no-progress --browsers=ChromeHeadlessCI

      - name: ensure documentation is buildable
        run: |
          npm run build:docs

      - name: ensure package compiles
        run: |
          npm run build

  slack-notification:
    needs: [npm-build]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.npm-build.outputs.status ) && github.ref_name == github.event.repository.default_branch }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v2
    with:
      job-status: ${{ needs.npm-build.outputs.status }}
