name: npm build

on: push

jobs:
  npm-build:
    name: CI Angular app through Github Actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: setup
        run: npm ci

      - name: run static tests
        run: |
          npm test -- --no-watch --watch=false --progress=false --no-progress --browsers=ChromeHeadlessCI

      - name: ensure documentation is buildable
        run: |
          npm run build:docs

      - name: ensure package compiles
        run: |
          npm run build
